name: urban_match
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # State Management
  flutter_riverpod: ^3.0.0-dev.3
  riverpod_annotation: ^3.0.0-dev.3

  # Routing
  auto_route: ^9.2.2

  # Models
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

  # API Calls
  dio: ^5.5.0+1

  # Logger
  logger: ^2.3.0

  # UI
  lucide_icons_flutter: ^3.0.4

  # Fuzzy Search
  fuzzywuzzy: ^1.1.6

  # environment variables
  flutter_dotenv: ^5.1.0

  google_maps_flutter: ^2.5.0
  http: ^1.1.0

  # App Version
  package_info_plus: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  lints: ^5.0.0

  # State Management
  riverpod_generator: ^3.0.0-dev.11

  # Routing
  auto_route_generator: ^9.0.0

  # Models
  freezed: ^2.5.2
  json_serializable: ^6.8.0

  # Code Generation
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - .env
  fonts:
    - family: SpaceGrotesk
      fonts:
        - asset: assets/fonts/SpaceGrotesk-Light.ttf
          weight: 300
        - asset: assets/fonts/SpaceGrotesk-Regular.ttf
          weight: 400
        - asset: assets/fonts/SpaceGrotesk-Medium.ttf
          weight: 500
        - asset: assets/fonts/SpaceGrotesk-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SpaceGrotesk-Bold.ttf
          weight: 700
    - family: TitanOne
      fonts:
        - asset: assets/fonts/TitanOne-Regular.ttf
          weight: 400
    - family: BricolageGrotesk
      fonts:
        - asset: assets/fonts/BricolageGrotesque-Regular.ttf
          weight: 400
        - asset: assets/fonts/BricolageGrotesque-Bold.ttf
          weight: 700
    - family: InstrumentSerif
      fonts:
        - asset: assets/fonts/InstrumentSerif-Regular.ttf
          weight: 400

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
